#!/bin/sh

if playerctl -s -p spotify status >/dev/null
then
	title="$(playerctl -s -p spotify metadata title)"
	artist="$(playerctl -s -p spotify metadata artist)"
	
	if [ -z "$title" ] || [ -z "$artist" ]
	then
		echo $artist$title
	else
		echo $artist - $title
	fi
else
	echo No Music
fi
