#!/bin/sh

playerctl -s -p spotify -F metadata -f '{{artist}} - {{title}}'  | while read -r line
do
	if [ "$line" = '' ] 
	then
		eww update player-opened=false
	else
		if [ "$line" = - ]
		then
			sleep 1

			artist="$(playerctl -s -p spotify metadata artist)"
			title="$(playerctl -s -p spotify metadata title)"

			if [ -z "$artist" ] || [ -z "$title" ]
			then
				continue
			fi

			line="$artist - $title"
		fi
		
		eww update "music=$line"
		eww update player-opened=true
	fi
done
