#!/bin/sh

playerctl -s -p spotify -F metadata -f '{{artist}} - {{title}}'  | while read -r line
do
	if [ "$line" = '' ] 
	then
		eww update player-opened=false
	else
		if [ "$line" = - ]
		then
			sleep 1

			line="$(playerctl -s -p spotify metadata artist) - $(playerctl -s -p spotify metadata title)"
		fi
		
		eww update "music=$line"
		eww update player-opened=true
	fi
done
