#!/bin/sh

playerctl -p "$PLAYER" -F metadata -f '{{artist}} - {{title}}' | while read -r line
do
	if [ "$line" = '' ]
	then
		eww update player-opened=false
	else
		if [ "$(eww get player-opened)" = false ]
		then
			sleep 1

			line="$(playerctl -p "$PLAYER" metadata -f '{{artist}} - {{title}}')"
		fi

		eww update player-opened=true
		eww update "player-music=$line"
	fi
done
