#!/bin/sh

playerctl -s -p "$PLAYER" -F metadata -f '{{artist}} - {{title}}'  | while read -r line
do
	if [ "$line" = '' ] 
	then
		eww update player-opened=false
	else
		if [ "$line" = - ]
		then
			sleep 1

			line="playerctl -s -p "$PLAYER" metadata -f '{{artist}} - {{title}}'"
		fi
		
		eww update "player-music=$line"
		eww update player-opened=true
	fi
done
