#!/bin/sh

adb shell settings put global sysui_demo_allowed 1 

adb shell am broadcast -a com.android.systemui.demo -e command clock -e hhmm 1200
adb shell am broadcast -a com.android.systemui.demo -e command network -e mobile show -e level 4 -e datatype false
adb shell am broadcast -a com.android.systemui.demo -e command notifications -e visible false
adb shell am broadcast -a com.android.systemui.demo -e command battery -e plugged false -e level 100

clean() {
	adb shell am broadcast -a com.android.systemui.demo -e command exit

	exit
}

trap clean INT

while true
do
	sleep 1
done
