#!/bin/sh

if [ "$HOSTNAME" != notebook ]
then
	exit 1
fi

is_enabled() {
	if [ -z "$(sudo wg)" ]
	then
		return 1
	fi
}

status() {
	if is_enabled
	then
		echo enabled
	else
		echo disabled
	fi
}

toggle() {
	if is_enabled
	then
		sudo wg-quick down "$VPN_INTERFACE"
	else
		sudo wg-quick up "$VPN_INTERFACE"
	fi
}

endpoint() {
	if is_enabled
	then
		sudo wg | grep 'endpoint: ' | awk -F 'endpoint: ' '{print $2}' 
	fi
}

case "$1" in
	status)
		status
		;;
	toggle)
		toggle
		;;
	endpoint)
		endpoint
		;;
	*)
		exit 1
		;;
esac
