#!/bin/sh

list () {
	seq 1 10 | jq --argjson windows "$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

all () {
	list

	socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r line
	do
		list
	done
}

current() {
	hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id'

	socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | stdbuf -o 0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}'
}

case "$1" in
	'all')
		all
		;;
	'current')
		current
		;;
	*)
		exit 1
		;;
esac
